# Generated by Django 5.2.4 on 2025-08-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Actividad')),
                ('categoria', models.CharField(choices=[('DEP', 'Deportes'), ('CUL', 'Cultural'), ('TEC', 'Tecnológica'), ('ART', 'Artística'), ('AMB', 'Ambiental'), ('SOC', 'Social'), ('LID', 'Liderazgo'), ('EMP', 'Emprendimiento'), ('VOL', 'Voluntariado'), ('CIE', 'Científica')], max_length=3, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Actividad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('centro_formacion', models.CharField(max_length=200, verbose_name='Centro de Formación')),
                ('regional', models.CharField(max_length=100, verbose_name='Regional')),
                ('estado', models.CharField(choices=[('PLA', 'Planificada'), ('ACT', 'Activa'), ('SUS', 'Suspendida'), ('FIN', 'Finalizada'), ('CAN', 'Cancelada')], default='PLA', max_length=3, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Actividad Extracurricular',
                'verbose_name_plural': 'Actividades Extracurricular',
                'ordering': ['nombre'],
            },
        ),
    ]
